name: Build Image
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      OUTPUT_FILE_PATH: ./deploy/image_$(date +\%Y-\%m-\%d)-Test-lite.zip

    steps:
    - name: Checkout code
      uses: actions/checkout@v1

    - name: Checkout contrail-cam repo
      uses: actions/checkout@v1
      with:
        repository: contrailcirrus/contrail-cameras
        path: contrail-cameras
        ref: 'Disable_ext_calibration'
        token: ${{ secrets.PAT_TOKEN }}

    - name: Set up dependencies
      run: |
        sudo apt-get update
        sudo apt-get install coreutils quilt parted qemu-user-static debootstrap zerofree zip dosfstools libarchive-tools libcap2-bin grep rsync xz-utils file git curl bc qemu-utils kpartx gpg pigz

    - name: Run build script
      run: |
        sudo chmod +x ./build.sh
        sudo ./build.sh

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: Raspberry-Pi-image
        path: ${{ env.OUTPUT_FILE_PATH }}
